# Generated by Django 4.2.6 on 2023-10-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_snippets_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
